title: "Dongyan's Blog"
description: "Explore the wonders of my world through this website."
author:
  name: "Dongyan Zhang"
  email: "zdy2303201737@outlook.com"

theme: jekyll-theme-cayman
theme_color: "#007BFF"

navigation:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Blog
    url: /blog

social_links:
  twitter: @dongyan0326
  github: Dongyan0326

paginate: 5
paginate_path: "/blog/page:num/"

markdown: kramdown
highlighter: rouge

